// Extensão: REST Client

### Create one
POST http://localhost:3000/films
Content-Type: application/json

{
    "title": "Castle in the Sky",
    "image": "https://image.tmdb.org/t/p/w600_and_h900_bestv2/npOnzAbLh6VOIu3naU5QaEcTepo.jpg",
    "movie_banner": "https://image.tmdb.org/t/p/w533_and_h300_bestv2/3cyjYtLWCBE1uvWINHFsFnE8LUK.jpg",
    "description": "he orphan Sheeta inherited a mysterious crystal that links her to the mythical sky-kingdom of Laputa. With the help of resourceful Pazu and a rollicking band of sky pirates, she makes her way to the ruins of the once-great civilization. Sheeta and Pazu must outwit the evil Muska, who plans to use Laputa's science to make himself ruler of the world.",
    "director": "Hayao Miyazaki",
    "producer": "Isao Takahata",
    "release_date": 1986
}

### Get All
GET http://localhost:3000/films

### Get One
GET http://localhost:3000/films/630babab07c1713b35a93074

### Delete One
DELETE  http://localhost:3000/films/630babab07c1713b35a93074

### Update One
PATCH  http://localhost:3000/films/630bc1ea9ce566007e386c06
Content-Type: application/json

{
    "title": "Picman"
}